'use client'
import { Toaster } from "react-hot-toast";
import "./globals.css";
import { usePathname } from "next/navigation";
import Navbar from "./components/Common/Navbar";



 const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  const pathname = usePathname()
  const hideNavbar = pathname.startsWith('/admin')
  return (
    <html lang="en">
      <body>
        {!hideNavbar && <Navbar />}
      <Toaster
  position="top-right"
  reverseOrder={false}
/>
        {children}
      </body>
    </html>
  );
}
