import { Toaster } from "react-hot-toast";
import "./globals.css";
import Navbar from "./components/Common/Navbar";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
      <Toaster
  position="top-right"
  reverseOrder={false}
/>
        {children}
      </body>
    </html>
  );
}
