import { Button } from "@/components/ui/button";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>

    <html lang="en">
      <body>
          <header className="flex justify-end items-center p-4 gap-4 h-16">
            <SignedOut>
            <Button variant={"outline"}>
            <SignInButton />
              </Button> 
              <SignUpButton />
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn>
          </header>
          {children}
        </body>
    </html>
    </ClerkProvider>
  );
}
